dist: xenial
sudo: required

language: python
python: "3.5"

virtualenv:
  system_site_packages: true

env:
  global:
    - TEST_RUN_FOLDER="/tmp" # folder where the tests are run from

matrix:
  # Do not wait for the allowed_failures entry to finish before
  # setting the status
  fast_finish: true
  allow_failures:
    # allow_failures seems to be keyed on the python version
    - python: 3.5
  include:
    # without matplotlib
    - env: DISTRIB="conda" PYTHON_VERSION="3.5"
           NUMPY_VERSION="1.11" SCIPY_VERSION="0.17"
           SCIKIT_LEARN_VERSION="0.18" COVERAGE="true"
           PANDAS_VERSION="*" NETWORKX_VERSION="*"
           FUTURE_VERSION="0.16.0" PACKAGING_VERSION="*"
           TRAITS_VERSION="4.6" SIMPLEJSON_VERSION="3.8.0"
           PROV_VERSION="1.5.0" FUNCSIGS_VERSION="*"
           CLICK_VERSION="6.6.0" TQDM_VERSION="4.19.5"
    - env: DISTRIB="conda" PYTHON_VERSION="3.5"
           NUMPY_VERSION="*" SCIPY_VERSION="*"
           SCIKIT_LEARN_VERSION="*" MATPLOTLIB_VERSION="*" COVERAGE="true"
           PANDAS_VERSION="*" NETWORKX_VERSION="*"
           FUTURE_VERSION="0.16.0" PACKAGING_VERSION="*"
           TRAITS_VERSION="4.6" SIMPLEJSON_VERSION="3.8.0"
           PROV_VERSION="1.5.0" FUNCSIGS_VERSION="*"
           CLICK_VERSION="6.6.0" TQDM_VERSION="4.19.5"
    - env: DISTRIB="conda" PYTHON_VERSION="3.6"
           NUMPY_VERSION="*" SCIPY_VERSION="*"
           SCIKIT_LEARN_VERSION="*" MATPLOTLIB_VERSION="*" COVERAGE="true"
           PANDAS_VERSION="*" NETWORKX_VERSION="*"
           FUTURE_VERSION="*" PACKAGING_VERSION="*"
           TRAITS_VERSION="*" SIMPLEJSON_VERSION="*"
           PROV_VERSION="*" FUNCSIGS_VERSION="*"
           CLICK_VERSION="*" TQDM_VERSION="*"
    - env: DISTRIB="conda" PYTHON_VERSION="3.7"
           NUMPY_VERSION="*" SCIPY_VERSION="*"
           SCIKIT_LEARN_VERSION="*" MATPLOTLIB_VERSION="*" COVERAGE="true"
           PANDAS_VERSION="*" NETWORKX_VERSION="*"
           FUTURE_VERSION="*" PACKAGING_VERSION="*"
           TRAITS_VERSION="*" SIMPLEJSON_VERSION="*"
           PROV_VERSION="*" FUNCSIGS_VERSION="*"
           CLICK_VERSION="6.7" TQDM_VERSION="*"

install: source continuous_integration/install.sh

before_script: make clean

script: source continuous_integration/test_script.sh

after_success: source continuous_integration/after_success.sh
